#!/bin/bash

ssh root@hvps <<EOSSH
cd /home/webneat

rm -rf tmp

git clone https://github.com/webNeat/react-tidy.git tmp
cd tmp/website
npm i
npm run build

rm -rf /var/www/html/react-tidy
mv build/react-tidy /var/www/html

cd ../..
rm -rf tmp
EOSSH