import {createMemoryStorage} from './createMemoryStorage'

describe('MemoryStorage', () => {
  test('it behaves like localStorage', () => {
    const storage = createMemoryStorage()
    expect(storage.getItem('foo')).toBeNull()
    expect(storage.getItem('bar')).toBeNull()
    expect(storage.length).toBe(0)
    storage.setItem('foo', 'lorem')
    expect(storage.getItem('foo')).toBe('lorem')
    expect(storage.getItem('bar')).toBeNull()
    expect(storage.length).toBe(1)
    expect(storage.key(0)).toBe('foo')
    expect(storage.key(1)).toBeNull()
    storage.setItem('bar', 'ipsum')
    expect(storage.getItem('foo')).toBe('lorem')
    expect(storage.getItem('bar')).toBe('ipsum')
    expect(storage.length).toBe(2)
    expect(storage.key(1)).toBe('bar')
    storage.removeItem('foo')
    expect(storage.getItem('foo')).toBeNull()
    expect(storage.getItem('bar')).toBe('ipsum')
    expect(storage.length).toBe(1)
    expect(storage.key(0)).toBe('bar')
    storage.clear()
    expect(storage.getItem('bar')).toBeNull()
    expect(storage.length).toBe(0)
  })
})
